name: Code Style Check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Install the project
      run: uv sync --locked --all-extras --dev

    - name: Run pylint
      run: uvx pylint --rcfile=.pylintrc *.py

    - name: Run black
      run: uvx black --check --diff --color *.py

    - name: Run isort
      run: uvx isort --check --diff *.py
